<Project>
  <PropertyGroup>
    <VersionPrefix>0.0.2</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
    <!-- SPDX license identifier for MIT -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <!-- Other useful metadata -->
    <RepositoryUrl>https://github.com/layeredcraft/dynamodb-efcore-provider</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Authors>Jonas Ha &amp; Nick Cipollina</Authors>
    <PackageProjectUrl>https://github.com/layeredcraft/dynamodb-efcore-provider</PackageProjectUrl>
    <Description>Entity Framework Core provider for AWS DynamoDB with LINQ-to-PartiQL translation, DynamoDB key modeling, and AWS SDK execution.</Description>
    <PackageTags>EntityFrameworkCore;EFCore;DynamoDB;AWS;PartiQL;database-provider</PackageTags>
    <PackageReleaseNotes>See the GitHub releases for version-specific changes.</PackageReleaseNotes>
    <PackageIcon>icon.png</PackageIcon>
    <!-- NuGet.org specific -->
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>embedded</DebugType>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <IsPackable>false</IsPackable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="" Visible="False" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Visible="False" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>