version: '3'

tasks:
  docs:serve:
    desc: Serve docs locally with Zensical
    cmds:
      - uv run zensical serve

  docs:build:
    desc: Build docs site with Zensical
    cmds:
      - uv run zensical build
